dockerui:
    image: abh1nav/dockerui
    container_name: dockerui_open_orchestra
    restart: always
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    ports:
        - 5000:9000
mongo-express:
    image: levino/mongo-express
    container_name: mongoexpress_open_orchestra
    ports:
        - 8081:8081
    links:
        - mongo:mongo
redis-commander:
    image: tenstartups/redis-commander
    container_name: rediscommander_open_orchestra
    links:
        - redis:redis
    command: --redis-host redis
    ports:
        - 8082:8081